package fr.thisismac.injector.customclass;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemDye;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.CraftingManager;

public class CustomCraft {
   public static void register() {
      ItemStack ame = new ItemStack(Items.amethyst, 1, 0);
      ItemStack gar = new ItemStack(Items.garnet, 1, 0);
      ItemStack xeno = new ItemStack(Items.xenotium, 1, 0);
      ItemStack manga = new ItemStack(Items.manganese, 1, 0);
      ItemStack tita = new ItemStack(Items.titanium, 1, 0);
      CraftingManager craft = CraftingManager.getInstance();
      craft.addRecipe(new ItemStack(Items.xenotium, 9, 1), new Object[]{"m", 'm', Items.xenotium});
      craft.addRecipe(new ItemStack(Items.amethyst, 9, 1), new Object[]{"m", 'm', Items.amethyst});
      craft.addRecipe(new ItemStack(Items.garnet, 9, 1), new Object[]{"m", 'm', Items.garnet});
      craft.addRecipe(new ItemStack(Items.titanium, 9, 1), new Object[]{"m", 'm', Items.titanium});
      craft.addRecipe(new ItemStack(Items.manganese, 9, 1), new Object[]{"m", 'm', Items.manganese});
      craft.addRecipe(new ItemStack(Items.obsidian, 9, 1), new Object[]{"m", 'm', Items.obsidian});
      craft.addRecipe(new ItemStack(Blocks.xtnt), new Object[]{"PMP", "PTP", "PMP", 'T', Blocks.tnt, 'M', new ItemStack(Items.xenotium, 1, 0), 'P', new ItemStack(Items.xenotium, 1, 1)});
      craft.addRecipe(new ItemStack(Blocks.renforced_glass, 1), new Object[]{"GC", 'C', Blocks.glass, 'G', Blocks.renforced_stone});
      craft.addRecipe(new ItemStack(Blocks.end_brick, 4), new Object[]{"   ", " SS", " SS", 'S', Blocks.end_stone});
      craft.addRecipe(new ItemStack(Blocks.custom_trapdoor, 1), new Object[]{"RRR", "VTV", "VVV", 'R', Items.redstone, 'T', Blocks.trapdoor, 'V', Blocks.glass});
      craft.addRecipe(new ItemStack(Blocks.obsidian_stair, 4), new Object[]{"O  ", "OO ", "OOO", 'O', Blocks.obsidian});
      craft.addRecipe(new ItemStack(Blocks.renforced_stone), new Object[]{"##", "##", '#', Blocks.cobblestone});
      craft.addRecipe(new ItemStack(Blocks.renforced_stone, 2), new Object[]{"   ", "XX ", "XX ", 'X', Blocks.cobblestone});
      craft.addRecipe(new ItemStack(Blocks.renforced_brick, 2), new Object[]{"   ", "   ", "XZ ", 'X', Blocks.renforced_stone, 'Z', Blocks.brick_block});
      craft.addRecipe(new ItemStack(Blocks.renforced_wood, 2), new Object[]{"   ", "   ", "XZ ", 'X', Blocks.renforced_stone, 'Z', Blocks.planks});
      craft.addRecipe(new ItemStack(Blocks.renforced_glass, 2), new Object[]{"GC", 'C', Blocks.glass, 'G', Blocks.renforced_stone});
      craft.addRecipe(new ItemStack(Block.getBlockFromName("netherwart_block"), 1), new Object[]{"kkk", "kkk", "kkk", 'k', Items.nether_wart});
      craft.addRecipe(new ItemStack(Block.getBlockFromName("red_netherbrick"), 1), new Object[]{"TG", "GT", 'T', Items.netherbrick, 'G', Items.nether_wart});
      craft.addRecipe(new ItemStack(Block.getBlockFromName("boneBlock"), 1), new Object[]{"ppp", "ppp", "ppp", 'p', new ItemStack(Items.dye, 1, 15)});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("manganese_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.manganese, 9, 0)});
      craft.addRecipe(new ItemStack(Items.manganese, 9, 0), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("manganese_block")});
      craft.addRecipe(new ItemStack(Items.manganese, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.manganese, 1, 1)});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("garnet_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.garnet, 9, 0)});
      craft.addRecipe(new ItemStack(Items.garnet, 9, 0), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("garnet_block")});
      craft.addRecipe(new ItemStack(Items.garnet, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.garnet, 1, 1)});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("obsidian_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.obsidian, 9, 0)});
      craft.addRecipe(new ItemStack(Items.obsidian, 9, 0), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("obsidian_block")});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("amethyst_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.amethyst, 9, 0)});
      craft.addRecipe(new ItemStack(Items.amethyst, 9, 0), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("amethyst_block")});
      craft.addRecipe(new ItemStack(Items.amethyst, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.amethyst, 1, 1)});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("titanium_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.titanium, 9, 0)});
      craft.addRecipe(new ItemStack(Items.titanium, 9, 0), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("titanium_block")});
      craft.addRecipe(new ItemStack(Items.titanium, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.titanium, 1, 1)});
      craft.addRecipe(new ItemStack(Items.titanium, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.obsidian, 1, 1)});
      craft.addRecipe(new ItemStack((Block)Block.blockRegistry.getObject("xenotium_block"), 1), new Object[]{"###", "###", "###", '#', new ItemStack(Items.xenotium, 9, 0)});
      craft.addRecipe(new ItemStack(Items.xenotium, 9), new Object[]{"#", '#', (Block)Block.blockRegistry.getObject("xenotium_block")});
      craft.addRecipe(new ItemStack(Items.xenotium, 1, 0), new Object[]{"lll", "lll", "lll", 'l', new ItemStack(Items.xenotium, 1, 1)});
      craft.addRecipe(new ItemStack(Items.core_titanium), new Object[]{" X ", "X#X", " X ", 'X', new ItemStack(Items.titanium, 1, 0), '#', Items.core_neutral});
      craft.addRecipe(new ItemStack(Items.core_obsidian), new Object[]{" X ", "X#X", " X ", 'X', new ItemStack(Items.obsidian, 1, 0), '#', Items.core_neutral});
      craft.addRecipe(new ItemStack(Items.core_xenotium), new Object[]{" X ", "X#X", " X ", 'X', new ItemStack(Items.xenotium, 1, 0), '#', Items.core_obsidian});
      craft.addRecipe(new ItemStack(Items.kebab, 5), new Object[]{"PPP", "BHB", "PPP", 'P', Items.bread, 'H', Items.cooked_chicken, 'B', Items.wheat});
      craft.addRecipe(new ItemStack(Items.cookie_garnet), new Object[]{"PPP", "GCG", "PPP", 'G', Block.getBlockFromName("garnet_block"), 'C', Items.cookie, 'P', Items.garnet});
      craft.addRecipe(new ItemStack(Items.cookie_amethyste), new Object[]{"PPP", "GCG", "PPP", 'G', Block.getBlockFromName("amethyst_block"), 'C', Items.cookie, 'P', Items.amethyst});
      craft.addRecipe(new ItemStack(Items.cookie_titanium), new Object[]{"PPP", "GCG", "PPP", 'G', Block.getBlockFromName("titanium_block"), 'C', Items.cookie, 'P', Items.titanium});
      craft.addRecipe(new ItemStack(Items.cookie_obsidian), new Object[]{"PPP", "GCG", "PPP", 'G', Block.getBlockFromName("obsidian_block"), 'C', Items.cookie, 'P', Items.obsidian});
      craft.addRecipe(new ItemStack(Items.customDoor), new Object[]{"RRR", "VPV", "VVV", 'R', Items.redstone, 'P', Items.iron_door, 'V', Blocks.glass});
      craft.addRecipe(new ItemStack(Blocks.iron_ladder), new Object[]{"X X", "XXX", "X X", 'X', Items.iron_ingot});
      craft.addRecipe(new ItemStack(Blocks.sadian_block), new Object[]{" X ", "X#X", " X ", 'X', Blocks.obsidian, '#', Blocks.sand});
      craft.addRecipe(new ItemStack(Items.joint), new Object[]{"CFC", "DFD", "CFC", 'C', Items.canabis, 'F', Items.paper, 'D', Blocks.dirt});
      craft.addRecipe(new ItemStack(Items.titanium_helmet), new Object[]{"X#X", "X X", 'X', new ItemStack(Items.titanium, 1, 0), '#', Items.core_titanium});
      craft.addRecipe(new ItemStack(Items.titanium_chestplate), new Object[]{"X X", "X#X", "XXX", 'X', new ItemStack(Items.titanium, 1, 0), '#', Items.core_titanium});
      craft.addRecipe(new ItemStack(Items.titanium_leggings), new Object[]{"X#X", "X X", "X X", 'X', new ItemStack(Items.titanium, 1, 0), '#', Items.core_titanium});
      craft.addRecipe(new ItemStack(Items.titanium_boots), new Object[]{"X X", "X#X", 'X', new ItemStack(Items.titanium, 1, 0), '#', Items.core_titanium});
      craft.addRecipe(new ItemStack(Items.manganese_helmet), new Object[]{"XXX", "X X", 'X', new ItemStack(Items.manganese, 1, 0)});
      craft.addRecipe(new ItemStack(Items.manganese_chestplate), new Object[]{"X X", "XXX", "XXX", 'X', new ItemStack(Items.manganese, 1, 0)});
      craft.addRecipe(new ItemStack(Items.manganese_leggings), new Object[]{"XXX", "X X", "X X", 'X', new ItemStack(Items.manganese, 1, 0)});
      craft.addRecipe(new ItemStack(Items.manganese_boots), new Object[]{"X X", "X X", 'X', new ItemStack(Items.manganese, 1, 0)});
      craft.addRecipe(new ItemStack(Items.garnet_helmet), new Object[]{"XXX", "X X", 'X', new ItemStack(Items.garnet, 1, 0)});
      craft.addRecipe(new ItemStack(Items.garnet_chestplate), new Object[]{"X X", "XXX", "XXX", 'X', new ItemStack(Items.garnet, 1, 0)});
      craft.addRecipe(new ItemStack(Items.garnet_leggings), new Object[]{"XXX", "X X", "X X", 'X', new ItemStack(Items.garnet, 1, 0)});
      craft.addRecipe(new ItemStack(Items.garnet_boots), new Object[]{"X X", "X X", 'X', new ItemStack(Items.garnet, 1, 0)});
      craft.addRecipe(new ItemStack(Items.amethyst_helmet), new Object[]{"XXX", "X X", 'X', new ItemStack(Items.amethyst, 1, 0)});
      craft.addRecipe(new ItemStack(Items.amethyst_chestplate), new Object[]{"X X", "XXX", "XXX", 'X', new ItemStack(Items.amethyst, 1, 0)});
      craft.addRecipe(new ItemStack(Items.amethyst_leggings), new Object[]{"XXX", "X X", "X X", 'X', new ItemStack(Items.amethyst, 1, 0)});
      craft.addRecipe(new ItemStack(Items.amethyst_boots), new Object[]{"X X", "X X", 'X', new ItemStack(Items.amethyst, 1, 0)});
      craft.addRecipe(new ItemStack(Items.obsidium_helmet), new Object[]{"XCX", "X X", "   ", 'X', Items.xenotium, 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_chestplate), new Object[]{"X X", "XCX", "XXX", 'X', Items.xenotium, 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_leggings), new Object[]{"XCX", "X X", "X X", 'X', Items.xenotium, 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_boots), new Object[]{"   ", "X X", "XCX", 'X', Items.xenotium, 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.bow_manganese), new Object[]{" #X", "# X", " #X", 'X', Items.string, '#', new ItemStack(Items.manganese, 1, 0)});
      craft.addRecipe(new ItemStack(Items.bow_garnet), new Object[]{" #X", "# X", " #X", 'X', Items.string, '#', new ItemStack(Items.garnet, 1, 0)});
      craft.addRecipe(new ItemStack(Items.bow_amethyst), new Object[]{" #X", "# X", " #X", 'X', Items.string, '#', new ItemStack(Items.amethyst, 1, 0)});
      craft.addRecipe(new ItemStack(Items.bow_titanium), new Object[]{" #X", "C X", " #X", 'C', Items.core_titanium, 'X', Items.string, '#', new ItemStack(Items.titanium, 1, 0)});
      craft.addRecipe(new ItemStack(Items.bow_obsidium), new Object[]{" #X", "C X", " #X", 'C', Items.core_xenotium, 'X', Items.string, '#', new ItemStack(Items.xenotium, 1, 0)});
      craft.addRecipe(new ItemStack(Items.manganese_sword), new Object[]{"X", "X", "#", 'X', manga, '#', Items.stick});
      craft.addRecipe(new ItemStack(Items.garnet_sword), new Object[]{"X", "X", "#", 'X', gar, '#', Items.stick});
      craft.addRecipe(new ItemStack(Items.amethyst_sword), new Object[]{"X", "X", "#", 'X', ame, '#', Items.stick});
      craft.addRecipe(new ItemStack(Items.titanium_sword), new Object[]{"X", "X", "#", 'X', tita, '#', Items.stick});
      craft.addRecipe(new ItemStack(Items.obsidium_sword), new Object[]{"X", "C", "#", 'C', Items.core_xenotium, 'X', xeno, '#', Items.stick});
      craft.addRecipe(new ItemStack(Items.manganese_pickaxe), new Object[]{"XXX", " # ", " # ", '#', Items.stick, 'X', manga});
      craft.addRecipe(new ItemStack(Items.manganese_shovel), new Object[]{"X", "#", "#", '#', Items.stick, 'X', manga});
      craft.addRecipe(new ItemStack(Items.manganese_axe), new Object[]{"XX", "X#", " #", '#', Items.stick, 'X', manga});
      craft.addRecipe(new ItemStack(Items.manganese_hoe), new Object[]{"XX", " #", " #", '#', Items.stick, 'X', manga});
      craft.addRecipe(new ItemStack(Items.garnet_pickaxe), new Object[]{"XXX", " # ", " # ", '#', Items.stick, 'X', gar});
      craft.addRecipe(new ItemStack(Items.garnet_shovel), new Object[]{"X", "#", "#", '#', Items.stick, 'X', gar});
      craft.addRecipe(new ItemStack(Items.garnet_axe), new Object[]{"XX", "X#", " #", '#', Items.stick, 'X', gar});
      craft.addRecipe(new ItemStack(Items.garnet_hoe), new Object[]{"XX", " #", " #", '#', Items.stick, 'X', gar});
      craft.addRecipe(new ItemStack(Items.amethyst_pickaxe), new Object[]{"XXX", " # ", " # ", '#', Items.stick, 'X', ame});
      craft.addRecipe(new ItemStack(Items.amethyst_shovel), new Object[]{"X", "#", "#", '#', Items.stick, 'X', ame});
      craft.addRecipe(new ItemStack(Items.amethyst_axe), new Object[]{"XX", "X#", " #", '#', Items.stick, 'X', ame});
      craft.addRecipe(new ItemStack(Items.amethyst_hoe), new Object[]{"XX", " #", " #", '#', Items.stick, 'X', ame});
      craft.addRecipe(new ItemStack(Items.titanium_pickaxe), new Object[]{"XZX", " # ", " # ", 'Z', Items.core_titanium, '#', Items.stick, 'X', tita});
      craft.addRecipe(new ItemStack(Items.titanium_shovel), new Object[]{"X", "#", "#", '#', Items.stick, 'Z', Items.core_titanium});
      craft.addRecipe(new ItemStack(Items.titanium_axe), new Object[]{"ZX", "X#", " #", 'Z', Items.core_titanium, '#', Items.stick, 'X', tita});
      craft.addRecipe(new ItemStack(Items.titanium_hoe), new Object[]{"ZX", " #", " #", 'Z', Items.core_titanium, '#', Items.stick, 'X', tita});
      craft.addRecipe(new ItemStack(Items.obsidium_pickaxe), new Object[]{"XCX", " # ", " # ", '#', Items.stick, 'X', new ItemStack(Items.xenotium, 1, 0), 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_shovel), new Object[]{" C ", " # ", " # ", '#', Items.stick, 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_axe), new Object[]{"CX ", "X# ", " # ", '#', Items.stick, 'X', new ItemStack(Items.xenotium, 1, 0), 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Items.obsidium_hoe), new Object[]{"CX ", " # ", " # ", '#', Items.stick, 'X', new ItemStack(Items.xenotium, 1, 0), 'C', Items.core_xenotium});
      craft.addRecipe(new ItemStack(Blocks.chest_garnet), new Object[]{"XXX", "XCX", "XXX", 'X', new ItemStack(Items.garnet, 1, 0), 'C', Blocks.chest});
      craft.addRecipe(new ItemStack(Blocks.chest_amethyst), new Object[]{"XXX", "XCX", "XXX", 'X', new ItemStack(Items.amethyst, 1, 0), 'C', Blocks.chest});
      craft.addRecipe(new ItemStack(Blocks.chest_titanium), new Object[]{"XXX", "XCX", "XXX", 'X', new ItemStack(Items.titanium, 1, 0), 'C', Blocks.chest});
      craft.addRecipe(new ItemStack(Blocks.chest_xenotium), new Object[]{" X ", "XCX", " X ", 'X', new ItemStack(Items.xenotium, 1, 0), 'C', Blocks.chest});

      for(int sub = 0; sub < 16; ++sub) {
         craft.addRecipe(new ItemStack(Block.getBlockFromName("hardened_stairs_" + ItemDye.field_150922_c[sub])), new Object[]{"X  ", "XX ", "XXX", 'X', new ItemStack(Blocks.stained_hardened_clay, 1, sub)});
      }
   }
}
