package fr.thisismac.injector.customclass;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCrystalIce extends ModelBase {
   ModelRenderer Head;
   ModelRenderer Spike_Base;
   ModelRenderer Spike_Basea;
   ModelRenderer Spike_Baseb;
   ModelRenderer Spike_Basec;
   ModelRenderer Spike_Based;
   ModelRenderer Spike_Basee;
   ModelRenderer Spike_Basef;
   ModelRenderer Spike_Baseg;
   ModelRenderer Spike_Baseh;
   ModelRenderer Spike_Basei;
   ModelRenderer Spike_Basej;
   ModelRenderer Spike_Basek;
   ModelRenderer Spike_Basel;
   ModelRenderer Spike_Basem;
   ModelRenderer Spike_Basen;
   ModelRenderer Spike_Baseo;
   ModelRenderer Spike_Basep;
   ModelRenderer Spike_Baseq;
   ModelRenderer Spike_Baser;
   ModelRenderer Spike_Bases;
   ModelRenderer Spike_Baset;
   ModelRenderer Spike_Baseu;
   ModelRenderer Spike_Basev;
   ModelRenderer Spike_Basew;
   ModelRenderer Spike_Basex;
   ModelRenderer Spike_Basey;
   ModelRenderer Spike_Basez;
   ModelRenderer Spike_Center;
   ModelRenderer Spike_Centera;
   ModelRenderer Spike_Centerb;
   ModelRenderer Spike_Centerc;
   ModelRenderer Spike_Centerd;
   ModelRenderer Spike_Centere;
   ModelRenderer Spike_Centerf;
   ModelRenderer Spike_Centerg;
   ModelRenderer Spike_Centerh;
   ModelRenderer Spike_Centeri;
   ModelRenderer Spike_Centerj;
   ModelRenderer Spike_Centerk;
   ModelRenderer Spike_Centerl;
   ModelRenderer Spike_Centerm;
   ModelRenderer Spike_Centern;
   ModelRenderer Spike_Centero;
   ModelRenderer Spike_Centerp;
   ModelRenderer Spike_Centerq;
   ModelRenderer Spike_Centerr;
   ModelRenderer Spike_Centers;
   ModelRenderer Spike_Centert;
   ModelRenderer Spike_Centeru;
   ModelRenderer Spike_Centerv;
   ModelRenderer Spike_Centerw;
   ModelRenderer Spike_Centerx;
   ModelRenderer Spike_Centery;
   ModelRenderer Spike_End;
   ModelRenderer Spike_Enda;
   ModelRenderer Spike_Endb;
   ModelRenderer Spike_Endc;
   ModelRenderer Spike_Endd;
   ModelRenderer Spike_Ende;
   ModelRenderer Spike_Endf;
   ModelRenderer Spike_Endg;
   ModelRenderer Spike_Endh;
   ModelRenderer Spike_Endi;
   ModelRenderer Spike_Endj;
   ModelRenderer Spike_Endk;
   ModelRenderer Spike_Endl;
   ModelRenderer Spike_Endm;
   ModelRenderer Spike_Endn;
   ModelRenderer Spike_Endo;
   ModelRenderer Spike_Endp;
   ModelRenderer Spike_Endq;
   ModelRenderer Spike_Endr;
   ModelRenderer Spike_Ends;
   ModelRenderer Spike_Endt;
   ModelRenderer Spike_Endu;
   ModelRenderer Spike_Endv;
   ModelRenderer Spike_Endw;
   ModelRenderer Spike_Endx;
   ModelRenderer Spike_Endy;

   public ModelCrystalIce() {
      this.textureWidth = 32;
      this.textureHeight = 37;
      this.Head = new ModelRenderer(this, 0, 0);
      this.Head.addBox(-4.0F, -4.0F, -4.0F, 8, 8, 8);
      this.Head.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Head.setTextureSize(32, 37);
      this.Head.mirror = true;
      this.setRotation(this.Head, 0.0F, 0.0F, 0.0F);
      this.Spike_Base = new ModelRenderer(this, 0, 27);
      this.Spike_Base.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Base.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Base.setTextureSize(32, 37);
      this.Spike_Base.mirror = true;
      this.setRotation(this.Spike_Base, -((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Basea = new ModelRenderer(this, 0, 27);
      this.Spike_Basea.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basea.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basea.setTextureSize(32, 37);
      this.Spike_Basea.mirror = true;
      this.setRotation(this.Spike_Basea, -2.356194F, 0.0F, 0.0F);
      this.Spike_Baseb = new ModelRenderer(this, 0, 27);
      this.Spike_Baseb.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseb.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseb.setTextureSize(32, 37);
      this.Spike_Baseb.mirror = true;
      this.setRotation(this.Spike_Baseb, 0.0F, 0.0F, 0.0F);
      this.Spike_Basec = new ModelRenderer(this, 0, 27);
      this.Spike_Basec.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basec.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basec.setTextureSize(32, 37);
      this.Spike_Basec.mirror = true;
      this.setRotation(this.Spike_Basec, 2.356194F, -((float)Math.PI / 4F), 0.0F);
      this.Spike_Based = new ModelRenderer(this, 0, 27);
      this.Spike_Based.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Based.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Based.setTextureSize(32, 37);
      this.Spike_Based.mirror = true;
      this.setRotation(this.Spike_Based, 2.356194F, 2.356194F, 0.0F);
      this.Spike_Basee = new ModelRenderer(this, 0, 27);
      this.Spike_Basee.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basee.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basee.setTextureSize(32, 37);
      this.Spike_Basee.mirror = true;
      this.setRotation(this.Spike_Basee, 2.356194F, ((float)Math.PI / 4F), 0.0F);
      this.Spike_Basef = new ModelRenderer(this, 0, 27);
      this.Spike_Basef.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basef.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basef.setTextureSize(32, 37);
      this.Spike_Basef.mirror = true;
      this.setRotation(this.Spike_Basef, 2.356194F, 0.0F, 0.0F);
      this.Spike_Baseg = new ModelRenderer(this, 0, 27);
      this.Spike_Baseg.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseg.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseg.setTextureSize(32, 37);
      this.Spike_Baseg.mirror = true;
      this.setRotation(this.Spike_Baseg, 0.0F, -((float)Math.PI / 4F), -((float)Math.PI / 2F));
      this.Spike_Baseh = new ModelRenderer(this, 0, 27);
      this.Spike_Baseh.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseh.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseh.setTextureSize(32, 37);
      this.Spike_Baseh.mirror = true;
      this.setRotation(this.Spike_Baseh, 0.0F, 2.356194F, -((float)Math.PI / 2F));
      this.Spike_Basei = new ModelRenderer(this, 0, 27);
      this.Spike_Basei.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basei.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basei.setTextureSize(32, 37);
      this.Spike_Basei.mirror = true;
      this.setRotation(this.Spike_Basei, 0.0F, ((float)Math.PI / 4F), -((float)Math.PI / 2F));
      this.Spike_Basej = new ModelRenderer(this, 0, 27);
      this.Spike_Basej.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basej.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basej.setTextureSize(32, 37);
      this.Spike_Basej.mirror = true;
      this.setRotation(this.Spike_Basej, 0.0F, 0.0F, -((float)Math.PI / 2F));
      this.Spike_Basek = new ModelRenderer(this, 0, 27);
      this.Spike_Basek.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basek.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basek.setTextureSize(32, 37);
      this.Spike_Basek.mirror = true;
      this.setRotation(this.Spike_Basek, 0.0F, ((float)Math.PI / 4F), ((float)Math.PI / 4F));
      this.Spike_Basel = new ModelRenderer(this, 0, 27);
      this.Spike_Basel.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basel.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basel.setTextureSize(32, 37);
      this.Spike_Basel.mirror = true;
      this.setRotation(this.Spike_Basel, 0.0F, -2.356194F, ((float)Math.PI / 4F));
      this.Spike_Basem = new ModelRenderer(this, 0, 27);
      this.Spike_Basem.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basem.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basem.setTextureSize(32, 37);
      this.Spike_Basem.mirror = true;
      this.setRotation(this.Spike_Basem, 0.0F, 2.356194F, ((float)Math.PI / 4F));
      this.Spike_Basen = new ModelRenderer(this, 0, 27);
      this.Spike_Basen.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basen.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basen.setTextureSize(32, 37);
      this.Spike_Basen.mirror = true;
      this.setRotation(this.Spike_Basen, 0.0F, 0.0F, -2.356194F);
      this.Spike_Baseo = new ModelRenderer(this, 0, 27);
      this.Spike_Baseo.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseo.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseo.setTextureSize(32, 37);
      this.Spike_Baseo.mirror = true;
      this.setRotation(this.Spike_Baseo, 0.0F, -((float)Math.PI / 4F), ((float)Math.PI / 4F));
      this.Spike_Basep = new ModelRenderer(this, 0, 27);
      this.Spike_Basep.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basep.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basep.setTextureSize(32, 37);
      this.Spike_Basep.mirror = true;
      this.setRotation(this.Spike_Basep, 0.0F, 0.0F, -((float)Math.PI / 4F));
      this.Spike_Baseq = new ModelRenderer(this, 0, 27);
      this.Spike_Baseq.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseq.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseq.setTextureSize(32, 37);
      this.Spike_Baseq.mirror = true;
      this.setRotation(this.Spike_Baseq, 0.0F, 0.0F, (float)Math.PI);
      this.Spike_Baser = new ModelRenderer(this, 0, 27);
      this.Spike_Baser.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baser.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baser.setTextureSize(32, 37);
      this.Spike_Baser.mirror = true;
      this.setRotation(this.Spike_Baser, 0.0F, 0.0F, 2.356194F);
      this.Spike_Bases = new ModelRenderer(this, 0, 27);
      this.Spike_Bases.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Bases.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Bases.setTextureSize(32, 37);
      this.Spike_Bases.mirror = true;
      this.setRotation(this.Spike_Bases, 0.0F, 0.0F, ((float)Math.PI / 2F));
      this.Spike_Baset = new ModelRenderer(this, 0, 27);
      this.Spike_Baset.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baset.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baset.setTextureSize(32, 37);
      this.Spike_Baset.mirror = true;
      this.setRotation(this.Spike_Baset, 0.0F, -2.356194F, -((float)Math.PI / 2F));
      this.Spike_Baseu = new ModelRenderer(this, 0, 27);
      this.Spike_Baseu.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Baseu.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Baseu.setTextureSize(32, 37);
      this.Spike_Baseu.mirror = true;
      this.setRotation(this.Spike_Baseu, ((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Basev = new ModelRenderer(this, 0, 27);
      this.Spike_Basev.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basev.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basev.setTextureSize(32, 37);
      this.Spike_Basev.mirror = true;
      this.setRotation(this.Spike_Basev, 0.0F, 0.0F, ((float)Math.PI / 4F));
      this.Spike_Basew = new ModelRenderer(this, 0, 27);
      this.Spike_Basew.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basew.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basew.setTextureSize(32, 37);
      this.Spike_Basew.mirror = true;
      this.setRotation(this.Spike_Basew, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Basex = new ModelRenderer(this, 0, 27);
      this.Spike_Basex.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basex.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basex.setTextureSize(32, 37);
      this.Spike_Basex.mirror = true;
      this.setRotation(this.Spike_Basex, (float)Math.PI, 0.0F, 0.0F);
      this.Spike_Basey = new ModelRenderer(this, 0, 27);
      this.Spike_Basey.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basey.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basey.setTextureSize(32, 37);
      this.Spike_Basey.mirror = true;
      this.setRotation(this.Spike_Basey, 2.356194F, -2.356194F, 0.0F);
      this.Spike_Basez = new ModelRenderer(this, 0, 27);
      this.Spike_Basez.addBox(-1.5F, -11.0F, -1.5F, 3, 7, 3);
      this.Spike_Basez.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Basez.setTextureSize(32, 37);
      this.Spike_Basez.mirror = true;
      this.setRotation(this.Spike_Basez, ((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Center = new ModelRenderer(this, 0, 20);
      this.Spike_Center.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Center.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Center.setTextureSize(32, 37);
      this.Spike_Center.mirror = true;
      this.setRotation(this.Spike_Center, -((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Centera = new ModelRenderer(this, 0, 20);
      this.Spike_Centera.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centera.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centera.setTextureSize(32, 37);
      this.Spike_Centera.mirror = true;
      this.setRotation(this.Spike_Centera, 0.0F, 0.0F, -2.356194F);
      this.Spike_Centerb = new ModelRenderer(this, 0, 20);
      this.Spike_Centerb.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerb.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerb.setTextureSize(32, 37);
      this.Spike_Centerb.mirror = true;
      this.setRotation(this.Spike_Centerb, ((float)Math.PI / 2F), ((float)Math.PI / 4F), 0.0F);
      this.Spike_Centerc = new ModelRenderer(this, 0, 20);
      this.Spike_Centerc.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerc.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerc.setTextureSize(32, 37);
      this.Spike_Centerc.mirror = true;
      this.setRotation(this.Spike_Centerc, ((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Centerd = new ModelRenderer(this, 0, 20);
      this.Spike_Centerd.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerd.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerd.setTextureSize(32, 37);
      this.Spike_Centerd.mirror = true;
      this.setRotation(this.Spike_Centerd, 2.356194F, ((float)Math.PI / 4F), 0.0F);
      this.Spike_Centere = new ModelRenderer(this, 0, 20);
      this.Spike_Centere.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centere.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centere.setTextureSize(32, 37);
      this.Spike_Centere.mirror = true;
      this.setRotation(this.Spike_Centere, (float)Math.PI, 0.0F, 0.0F);
      this.Spike_Centerf = new ModelRenderer(this, 0, 20);
      this.Spike_Centerf.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerf.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerf.setTextureSize(32, 37);
      this.Spike_Centerf.mirror = true;
      this.setRotation(this.Spike_Centerf, -2.356194F, 0.0F, 0.0F);
      this.Spike_Centerg = new ModelRenderer(this, 0, 20);
      this.Spike_Centerg.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerg.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerg.setTextureSize(32, 37);
      this.Spike_Centerg.mirror = true;
      this.setRotation(this.Spike_Centerg, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Centerh = new ModelRenderer(this, 0, 20);
      this.Spike_Centerh.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerh.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerh.setTextureSize(32, 37);
      this.Spike_Centerh.mirror = true;
      this.setRotation(this.Spike_Centerh, 0.0F, 0.0F, ((float)Math.PI / 4F));
      this.Spike_Centeri = new ModelRenderer(this, 0, 20);
      this.Spike_Centeri.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centeri.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centeri.setTextureSize(32, 37);
      this.Spike_Centeri.mirror = true;
      this.setRotation(this.Spike_Centeri, 0.0F, 0.0F, ((float)Math.PI / 2F));
      this.Spike_Centerj = new ModelRenderer(this, 0, 20);
      this.Spike_Centerj.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerj.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerj.setTextureSize(32, 37);
      this.Spike_Centerj.mirror = true;
      this.setRotation(this.Spike_Centerj, 0.0F, 0.0F, 2.356194F);
      this.Spike_Centerk = new ModelRenderer(this, 0, 20);
      this.Spike_Centerk.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerk.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerk.setTextureSize(32, 37);
      this.Spike_Centerk.mirror = true;
      this.setRotation(this.Spike_Centerk, 0.0F, ((float)Math.PI / 4F), -((float)Math.PI / 4F));
      this.Spike_Centerl = new ModelRenderer(this, 0, 20);
      this.Spike_Centerl.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerl.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerl.setTextureSize(32, 37);
      this.Spike_Centerl.mirror = true;
      this.setRotation(this.Spike_Centerl, 0.0F, 0.0F, -((float)Math.PI / 2F));
      this.Spike_Centerm = new ModelRenderer(this, 0, 20);
      this.Spike_Centerm.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerm.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerm.setTextureSize(32, 37);
      this.Spike_Centerm.mirror = true;
      this.setRotation(this.Spike_Centerm, 0.0F, 0.0F, -((float)Math.PI / 4F));
      this.Spike_Centern = new ModelRenderer(this, 0, 20);
      this.Spike_Centern.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centern.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centern.setTextureSize(32, 37);
      this.Spike_Centern.mirror = true;
      this.setRotation(this.Spike_Centern, 0.0F, -((float)Math.PI / 4F), -((float)Math.PI / 4F));
      this.Spike_Centero = new ModelRenderer(this, 0, 20);
      this.Spike_Centero.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centero.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centero.setTextureSize(32, 37);
      this.Spike_Centero.mirror = true;
      this.setRotation(this.Spike_Centero, 0.0F, -2.356194F, -((float)Math.PI / 4F));
      this.Spike_Centerp = new ModelRenderer(this, 0, 20);
      this.Spike_Centerp.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerp.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerp.setTextureSize(32, 37);
      this.Spike_Centerp.mirror = true;
      this.setRotation(this.Spike_Centerp, 0.0F, 2.356194F, -((float)Math.PI / 4F));
      this.Spike_Centerq = new ModelRenderer(this, 0, 20);
      this.Spike_Centerq.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerq.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerq.setTextureSize(32, 37);
      this.Spike_Centerq.mirror = true;
      this.setRotation(this.Spike_Centerq, ((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Centerr = new ModelRenderer(this, 0, 20);
      this.Spike_Centerr.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerr.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerr.setTextureSize(32, 37);
      this.Spike_Centerr.mirror = true;
      this.setRotation(this.Spike_Centerr, ((float)Math.PI / 2F), -((float)Math.PI / 4F), 0.0F);
      this.Spike_Centers = new ModelRenderer(this, 0, 20);
      this.Spike_Centers.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centers.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centers.setTextureSize(32, 37);
      this.Spike_Centers.mirror = true;
      this.setRotation(this.Spike_Centers, ((float)Math.PI / 2F), -2.356194F, 0.0F);
      this.Spike_Centert = new ModelRenderer(this, 0, 20);
      this.Spike_Centert.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centert.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centert.setTextureSize(32, 37);
      this.Spike_Centert.mirror = true;
      this.setRotation(this.Spike_Centert, ((float)Math.PI / 2F), 2.356194F, 0.0F);
      this.Spike_Centeru = new ModelRenderer(this, 0, 20);
      this.Spike_Centeru.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centeru.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centeru.setTextureSize(32, 37);
      this.Spike_Centeru.mirror = true;
      this.setRotation(this.Spike_Centeru, 2.356194F, 0.0F, 0.0F);
      this.Spike_Centerv = new ModelRenderer(this, 0, 20);
      this.Spike_Centerv.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerv.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerv.setTextureSize(32, 37);
      this.Spike_Centerv.mirror = true;
      this.setRotation(this.Spike_Centerv, 2.356194F, -((float)Math.PI / 4F), 0.0F);
      this.Spike_Centerw = new ModelRenderer(this, 0, 20);
      this.Spike_Centerw.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerw.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerw.setTextureSize(32, 37);
      this.Spike_Centerw.mirror = true;
      this.setRotation(this.Spike_Centerw, 2.356194F, -2.356194F, 0.0F);
      this.Spike_Centerx = new ModelRenderer(this, 0, 20);
      this.Spike_Centerx.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centerx.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centerx.setTextureSize(32, 37);
      this.Spike_Centerx.mirror = true;
      this.setRotation(this.Spike_Centerx, 2.356194F, 2.356194F, 0.0F);
      this.Spike_Centery = new ModelRenderer(this, 0, 20);
      this.Spike_Centery.addBox(-1.0F, -16.0F, -1.0F, 2, 5, 2);
      this.Spike_Centery.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Centery.setTextureSize(32, 37);
      this.Spike_Centery.mirror = true;
      this.setRotation(this.Spike_Centery, 0.0F, 0.0F, 0.0F);
      this.Spike_End = new ModelRenderer(this, 0, 16);
      this.Spike_End.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_End.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_End.setTextureSize(32, 37);
      this.Spike_End.mirror = true;
      this.setRotation(this.Spike_End, (float)Math.PI, 0.0F, 0.0F);
      this.Spike_Enda = new ModelRenderer(this, 0, 16);
      this.Spike_Enda.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Enda.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Enda.setTextureSize(32, 37);
      this.Spike_Enda.mirror = true;
      this.setRotation(this.Spike_Enda, 0.0F, 0.0F, -((float)Math.PI / 4F));
      this.Spike_Endb = new ModelRenderer(this, 0, 16);
      this.Spike_Endb.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endb.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endb.setTextureSize(32, 37);
      this.Spike_Endb.mirror = true;
      this.setRotation(this.Spike_Endb, ((float)Math.PI / 4F), -((float)Math.PI / 4F), 0.0F);
      this.Spike_Endc = new ModelRenderer(this, 0, 16);
      this.Spike_Endc.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endc.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endc.setTextureSize(32, 37);
      this.Spike_Endc.mirror = true;
      this.setRotation(this.Spike_Endc, ((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Endd = new ModelRenderer(this, 0, 16);
      this.Spike_Endd.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endd.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endd.setTextureSize(32, 37);
      this.Spike_Endd.mirror = true;
      this.setRotation(this.Spike_Endd, 2.356194F, 0.0F, 0.0F);
      this.Spike_Ende = new ModelRenderer(this, 0, 16);
      this.Spike_Ende.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Ende.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Ende.setTextureSize(32, 37);
      this.Spike_Ende.mirror = true;
      this.setRotation(this.Spike_Ende, -2.356194F, 0.0F, 0.0F);
      this.Spike_Endf = new ModelRenderer(this, 0, 16);
      this.Spike_Endf.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endf.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endf.setTextureSize(32, 37);
      this.Spike_Endf.mirror = true;
      this.setRotation(this.Spike_Endf, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.Spike_Endg = new ModelRenderer(this, 0, 16);
      this.Spike_Endg.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endg.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endg.setTextureSize(32, 37);
      this.Spike_Endg.mirror = true;
      this.setRotation(this.Spike_Endg, -((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Endh = new ModelRenderer(this, 0, 16);
      this.Spike_Endh.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endh.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endh.setTextureSize(32, 37);
      this.Spike_Endh.mirror = true;
      this.setRotation(this.Spike_Endh, 0.0F, 0.0F, 0.0F);
      this.Spike_Endi = new ModelRenderer(this, 0, 16);
      this.Spike_Endi.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endi.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endi.setTextureSize(32, 37);
      this.Spike_Endi.mirror = true;
      this.setRotation(this.Spike_Endi, 0.0F, 0.0F, ((float)Math.PI / 4F));
      this.Spike_Endj = new ModelRenderer(this, 0, 16);
      this.Spike_Endj.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endj.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endj.setTextureSize(32, 37);
      this.Spike_Endj.mirror = true;
      this.setRotation(this.Spike_Endj, 0.0F, 0.0F, ((float)Math.PI / 2F));
      this.Spike_Endk = new ModelRenderer(this, 0, 16);
      this.Spike_Endk.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endk.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endk.setTextureSize(32, 37);
      this.Spike_Endk.mirror = true;
      this.setRotation(this.Spike_Endk, 0.0F, 0.0F, 2.356194F);
      this.Spike_Endl = new ModelRenderer(this, 0, 16);
      this.Spike_Endl.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endl.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endl.setTextureSize(32, 37);
      this.Spike_Endl.mirror = true;
      this.setRotation(this.Spike_Endl, 0.0F, -2.356194F, -2.356194F);
      this.Spike_Endm = new ModelRenderer(this, 0, 16);
      this.Spike_Endm.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endm.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endm.setTextureSize(32, 37);
      this.Spike_Endm.mirror = true;
      this.setRotation(this.Spike_Endm, 0.0F, -((float)Math.PI / 4F), -((float)Math.PI / 2F));
      this.Spike_Endn = new ModelRenderer(this, 0, 16);
      this.Spike_Endn.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endn.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endn.setTextureSize(32, 37);
      this.Spike_Endn.mirror = true;
      this.setRotation(this.Spike_Endn, 0.0F, 0.0F, -((float)Math.PI / 2F));
      this.Spike_Endo = new ModelRenderer(this, 0, 16);
      this.Spike_Endo.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endo.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endo.setTextureSize(32, 37);
      this.Spike_Endo.mirror = true;
      this.setRotation(this.Spike_Endo, 0.0F, ((float)Math.PI / 4F), -((float)Math.PI / 2F));
      this.Spike_Endp = new ModelRenderer(this, 0, 16);
      this.Spike_Endp.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endp.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endp.setTextureSize(32, 37);
      this.Spike_Endp.mirror = true;
      this.setRotation(this.Spike_Endp, 0.0F, 2.356194F, -((float)Math.PI / 2F));
      this.Spike_Endq = new ModelRenderer(this, 0, 16);
      this.Spike_Endq.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endq.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endq.setTextureSize(32, 37);
      this.Spike_Endq.mirror = true;
      this.setRotation(this.Spike_Endq, 0.0F, -2.356194F, -((float)Math.PI / 2F));
      this.Spike_Endr = new ModelRenderer(this, 0, 16);
      this.Spike_Endr.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endr.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endr.setTextureSize(32, 37);
      this.Spike_Endr.mirror = true;
      this.setRotation(this.Spike_Endr, ((float)Math.PI / 4F), 0.0F, 0.0F);
      this.Spike_Ends = new ModelRenderer(this, 0, 16);
      this.Spike_Ends.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Ends.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Ends.setTextureSize(32, 37);
      this.Spike_Ends.mirror = true;
      this.setRotation(this.Spike_Ends, ((float)Math.PI / 4F), ((float)Math.PI / 4F), 0.0F);
      this.Spike_Endt = new ModelRenderer(this, 0, 16);
      this.Spike_Endt.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endt.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endt.setTextureSize(32, 37);
      this.Spike_Endt.mirror = true;
      this.setRotation(this.Spike_Endt, ((float)Math.PI / 4F), 2.356194F, 0.0F);
      this.Spike_Endu = new ModelRenderer(this, 0, 16);
      this.Spike_Endu.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endu.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endu.setTextureSize(32, 37);
      this.Spike_Endu.mirror = true;
      this.setRotation(this.Spike_Endu, ((float)Math.PI / 4F), -2.356194F, 0.0F);
      this.Spike_Endv = new ModelRenderer(this, 0, 16);
      this.Spike_Endv.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endv.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endv.setTextureSize(32, 37);
      this.Spike_Endv.mirror = true;
      this.setRotation(this.Spike_Endv, 0.0F, 0.0F, -2.356194F);
      this.Spike_Endw = new ModelRenderer(this, 0, 16);
      this.Spike_Endw.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endw.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endw.setTextureSize(32, 37);
      this.Spike_Endw.mirror = true;
      this.setRotation(this.Spike_Endw, 0.0F, -((float)Math.PI / 4F), -2.356194F);
      this.Spike_Endx = new ModelRenderer(this, 0, 16);
      this.Spike_Endx.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endx.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endx.setTextureSize(32, 37);
      this.Spike_Endx.mirror = true;
      this.setRotation(this.Spike_Endx, 0.0F, ((float)Math.PI / 4F), -2.356194F);
      this.Spike_Endy = new ModelRenderer(this, 0, 16);
      this.Spike_Endy.addBox(-0.5F, -19.0F, -0.5F, 1, 3, 1);
      this.Spike_Endy.setRotationPoint(0.0F, 7.0F, 0.0F);
      this.Spike_Endy.setTextureSize(32, 37);
      this.Spike_Endy.mirror = true;
      this.setRotation(this.Spike_Endy, 0.0F, 2.356194F, -2.356194F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.Head.render(f5);
      this.Spike_Base.render(f5);
      this.Spike_Basea.render(f5);
      this.Spike_Baseb.render(f5);
      this.Spike_Basec.render(f5);
      this.Spike_Based.render(f5);
      this.Spike_Basee.render(f5);
      this.Spike_Basef.render(f5);
      this.Spike_Baseg.render(f5);
      this.Spike_Baseh.render(f5);
      this.Spike_Basei.render(f5);
      this.Spike_Basej.render(f5);
      this.Spike_Basek.render(f5);
      this.Spike_Basel.render(f5);
      this.Spike_Basem.render(f5);
      this.Spike_Basen.render(f5);
      this.Spike_Baseo.render(f5);
      this.Spike_Basep.render(f5);
      this.Spike_Baseq.render(f5);
      this.Spike_Baser.render(f5);
      this.Spike_Bases.render(f5);
      this.Spike_Baset.render(f5);
      this.Spike_Baseu.render(f5);
      this.Spike_Basev.render(f5);
      this.Spike_Basew.render(f5);
      this.Spike_Basex.render(f5);
      this.Spike_Basey.render(f5);
      this.Spike_Basez.render(f5);
      this.Spike_Center.render(f5);
      this.Spike_Centera.render(f5);
      this.Spike_Centerb.render(f5);
      this.Spike_Centerc.render(f5);
      this.Spike_Centerd.render(f5);
      this.Spike_Centere.render(f5);
      this.Spike_Centerf.render(f5);
      this.Spike_Centerg.render(f5);
      this.Spike_Centerh.render(f5);
      this.Spike_Centeri.render(f5);
      this.Spike_Centerj.render(f5);
      this.Spike_Centerk.render(f5);
      this.Spike_Centerl.render(f5);
      this.Spike_Centerm.render(f5);
      this.Spike_Centern.render(f5);
      this.Spike_Centero.render(f5);
      this.Spike_Centerp.render(f5);
      this.Spike_Centerq.render(f5);
      this.Spike_Centerr.render(f5);
      this.Spike_Centers.render(f5);
      this.Spike_Centert.render(f5);
      this.Spike_Centeru.render(f5);
      this.Spike_Centerv.render(f5);
      this.Spike_Centerw.render(f5);
      this.Spike_Centerx.render(f5);
      this.Spike_Centery.render(f5);
      this.Spike_End.render(f5);
      this.Spike_Enda.render(f5);
      this.Spike_Endb.render(f5);
      this.Spike_Endc.render(f5);
      this.Spike_Endd.render(f5);
      this.Spike_Ende.render(f5);
      this.Spike_Endf.render(f5);
      this.Spike_Endg.render(f5);
      this.Spike_Endh.render(f5);
      this.Spike_Endi.render(f5);
      this.Spike_Endj.render(f5);
      this.Spike_Endk.render(f5);
      this.Spike_Endl.render(f5);
      this.Spike_Endm.render(f5);
      this.Spike_Endn.render(f5);
      this.Spike_Endo.render(f5);
      this.Spike_Endp.render(f5);
      this.Spike_Endq.render(f5);
      this.Spike_Endr.render(f5);
      this.Spike_Ends.render(f5);
      this.Spike_Endt.render(f5);
      this.Spike_Endu.render(f5);
      this.Spike_Endv.render(f5);
      this.Spike_Endw.render(f5);
      this.Spike_Endx.render(f5);
      this.Spike_Endy.render(f5);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
   }
}
