package fr.thisismac.injector.customclass;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCraftmanBackPack extends ModelBase {
   ModelRenderer MainCusion;
   ModelRenderer Bag1;
   ModelRenderer Bag2;
   ModelRenderer Pouch1;
   ModelRenderer Pouch2;
   ModelRenderer LeftStrap1;
   ModelRenderer LeftStrap2;
   ModelRenderer LeftStrap3;
   ModelRenderer RightStrap1;
   ModelRenderer RightStrap2;
   ModelRenderer RightStrap3;
   ModelRenderer BenchTable;
   ModelRenderer BenchLeg1;
   ModelRenderer BenchLeg2;
   ModelRenderer BenchLeg3;
   ModelRenderer BenchLeg4;
   ModelRenderer Rod1;
   ModelRenderer Rod2;
   ModelRenderer Rod3;
   ModelRenderer Rod4;
   ModelRenderer MalletHandle;
   ModelRenderer MalletHead;
   ModelRenderer MasonsHammerHead;
   ModelRenderer MasonsHammerHandle;
   ModelRenderer SawBlade;
   ModelRenderer SawTeeth;
   ModelRenderer SawHandle1;
   ModelRenderer SawHandle2;
   ModelRenderer SawHandle3;
   ModelRenderer SawHandle4;
   ModelRenderer Peg1;
   ModelRenderer TongsHandle1;
   ModelRenderer TongsHandle2;
   ModelRenderer TongsHub;
   ModelRenderer Tongs1;
   ModelRenderer Tongs2;
   ModelRenderer Plans1;
   ModelRenderer Plans2;
   ModelRenderer TackHammerHandle;
   ModelRenderer TackHammerHead;
   ModelRenderer StraightLine;
   ModelRenderer SledgehammerHead;
   ModelRenderer SledgehammerHandle;
   ModelRenderer Peg2;
   ModelRenderer Peg3;

   public ModelCraftmanBackPack() {
      this.textureWidth = 64;
      this.textureHeight = 64;
      this.MainCusion = new ModelRenderer(this, 28, 50);
      this.MainCusion.addBox(0.0F, 0.0F, 0.0F, 8, 10, 3);
      this.MainCusion.setRotationPoint(-4.0F, 0.0F, 2.0F);
      this.MainCusion.setTextureSize(64, 64);
      this.MainCusion.mirror = true;
      this.setRotation(this.MainCusion, 0.0F, 0.0F, 0.0F);
      this.Bag1 = new ModelRenderer(this, 0, 50);
      this.Bag1.addBox(0.0F, 0.0F, 0.0F, 4, 4, 3);
      this.Bag1.setRotationPoint(-4.0F, 5.0F, 2.5F);
      this.Bag1.setTextureSize(64, 64);
      this.Bag1.mirror = true;
      this.setRotation(this.Bag1, 0.0F, -((float)Math.PI / 2F), 0.0F);
      this.Bag2 = new ModelRenderer(this, 0, 50);
      this.Bag2.addBox(0.0F, 0.0F, 0.0F, 4, 4, 3);
      this.Bag2.setRotationPoint(4.0F, 5.0F, 6.5F);
      this.Bag2.setTextureSize(64, 64);
      this.Bag2.mirror = true;
      this.setRotation(this.Bag2, 0.0F, ((float)Math.PI / 2F), 0.0F);
      this.Pouch1 = new ModelRenderer(this, 0, 57);
      this.Pouch1.addBox(0.0F, 0.0F, 0.0F, 2, 4, 3);
      this.Pouch1.setRotationPoint(-4.0F, 1.0F, 6.0F);
      this.Pouch1.setTextureSize(64, 64);
      this.Pouch1.mirror = true;
      this.setRotation(this.Pouch1, 0.0F, (float)Math.PI, 0.0F);
      this.Pouch2 = new ModelRenderer(this, 0, 57);
      this.Pouch2.addBox(-2.0F, 0.0F, -3.0F, 2, 4, 3);
      this.Pouch2.setRotationPoint(6.0F, 1.0F, 6.0F);
      this.Pouch2.setTextureSize(64, 64);
      this.Pouch2.mirror = true;
      this.setRotation(this.Pouch2, 0.0F, 0.0F, 0.0F);
      this.LeftStrap1 = new ModelRenderer(this, 4, 0);
      this.LeftStrap1.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.LeftStrap1.setRotationPoint(3.6F, -0.5F, 3.0F);
      this.LeftStrap1.setTextureSize(64, 64);
      this.LeftStrap1.mirror = true;
      this.setRotation(this.LeftStrap1, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.LeftStrap2 = new ModelRenderer(this, 10, 0);
      this.LeftStrap2.addBox(-1.0F, 0.0F, 0.0F, 1, 8, 1);
      this.LeftStrap2.setRotationPoint(4.6F, 0.5F, -3.0F);
      this.LeftStrap2.setTextureSize(64, 64);
      this.LeftStrap2.mirror = true;
      this.setRotation(this.LeftStrap2, 0.0F, 0.0F, 0.0349066F);
      this.LeftStrap3 = new ModelRenderer(this, 4, 0);
      this.LeftStrap3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.LeftStrap3.setRotationPoint(3.4F, 8.0F, 3.0F);
      this.LeftStrap3.setTextureSize(64, 64);
      this.LeftStrap3.mirror = true;
      this.setRotation(this.LeftStrap3, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.RightStrap1 = new ModelRenderer(this, 4, 0);
      this.RightStrap1.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.RightStrap1.setRotationPoint(-4.6F, -0.5F, 3.0F);
      this.RightStrap1.setTextureSize(64, 64);
      this.RightStrap1.mirror = true;
      this.setRotation(this.RightStrap1, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.RightStrap2 = new ModelRenderer(this, 10, 0);
      this.RightStrap2.addBox(0.0F, 0.0F, 0.0F, 1, 8, 1);
      this.RightStrap2.setRotationPoint(-4.6F, 0.5F, -3.0F);
      this.RightStrap2.setTextureSize(64, 64);
      this.RightStrap2.mirror = true;
      this.setRotation(this.RightStrap2, 0.0F, 0.0F, -0.0349066F);
      this.RightStrap3 = new ModelRenderer(this, 4, 0);
      this.RightStrap3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.RightStrap3.setRotationPoint(-4.4F, 8.0F, 3.0F);
      this.RightStrap3.setTextureSize(64, 64);
      this.RightStrap3.mirror = true;
      this.setRotation(this.RightStrap3, -((float)Math.PI / 2F), 0.0F, 0.0F);
      this.BenchTable = new ModelRenderer(this, 32, 0);
      this.BenchTable.addBox(0.0F, 0.0F, 0.0F, 8, 15, 2);
      this.BenchTable.setRotationPoint(-4.0F, -3.0F, 5.0F);
      this.BenchTable.setTextureSize(64, 64);
      this.BenchTable.mirror = true;
      this.setRotation(this.BenchTable, 0.0F, 0.0F, 0.0F);
      this.BenchLeg1 = new ModelRenderer(this, 0, 16);
      this.BenchLeg1.addBox(0.0F, 0.0F, 0.0F, 2, 5, 2);
      this.BenchLeg1.setRotationPoint(1.5F, -1.0F, 7.0F);
      this.BenchLeg1.setTextureSize(64, 64);
      this.BenchLeg1.mirror = true;
      this.setRotation(this.BenchLeg1, 1.762782F, 0.1396263F, 0.2617994F);
      this.BenchLeg2 = new ModelRenderer(this, 0, 16);
      this.BenchLeg2.addBox(-2.0F, 0.0F, 0.0F, 2, 5, 2);
      this.BenchLeg2.setRotationPoint(-1.5F, -1.0F, 7.0F);
      this.BenchLeg2.setTextureSize(64, 64);
      this.BenchLeg2.mirror = true;
      this.setRotation(this.BenchLeg2, 1.762782F, -0.1396263F, -0.2617994F);
      this.BenchLeg3 = new ModelRenderer(this, 0, 16);
      this.BenchLeg3.addBox(0.0F, 0.0F, -2.0F, 2, 5, 2);
      this.BenchLeg3.setRotationPoint(1.5F, 10.0F, 7.0F);
      this.BenchLeg3.setTextureSize(64, 64);
      this.BenchLeg3.mirror = true;
      this.setRotation(this.BenchLeg3, 1.37881F, 0.1396263F, -0.2617994F);
      this.BenchLeg4 = new ModelRenderer(this, 0, 16);
      this.BenchLeg4.addBox(-2.0F, 0.0F, -2.0F, 2, 5, 2);
      this.BenchLeg4.setRotationPoint(-1.5F, 10.0F, 7.0F);
      this.BenchLeg4.setTextureSize(64, 64);
      this.BenchLeg4.mirror = true;
      this.setRotation(this.BenchLeg4, 1.37881F, -0.1396263F, 0.2617994F);
      this.Rod1 = new ModelRenderer(this, 0, 0);
      this.Rod1.addBox(0.0F, 0.0F, 0.0F, 1, 13, 1);
      this.Rod1.setRotationPoint(3.0F, -2.0F, 9.0F);
      this.Rod1.setTextureSize(64, 64);
      this.Rod1.mirror = true;
      this.setRotation(this.Rod1, 0.0F, 0.1919862F, 0.0F);
      this.Rod2 = new ModelRenderer(this, 0, 0);
      this.Rod2.addBox(-1.0F, 0.0F, 0.0F, 1, 13, 1);
      this.Rod2.setRotationPoint(-3.0F, -2.0F, 9.0F);
      this.Rod2.setTextureSize(64, 64);
      this.Rod2.mirror = true;
      this.setRotation(this.Rod2, 0.0F, -0.1919862F, 0.0F);
      this.Rod3 = new ModelRenderer(this, 0, 0);
      this.Rod3.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.Rod3.setRotationPoint(-3.0F, -2.0F, 10.0F);
      this.Rod3.setTextureSize(64, 64);
      this.Rod3.mirror = true;
      this.setRotation(this.Rod3, ((float)Math.PI / 2F), ((float)Math.PI / 2F), 0.1919862F);
      this.Rod4 = new ModelRenderer(this, 0, 0);
      this.Rod4.addBox(0.0F, 0.0F, -1.0F, 1, 6, 1);
      this.Rod4.setRotationPoint(-3.0F, 11.0F, 10.0F);
      this.Rod4.setTextureSize(64, 64);
      this.Rod4.mirror = true;
      this.setRotation(this.Rod4, ((float)Math.PI / 2F), ((float)Math.PI / 2F), -0.1919862F);
      this.MalletHandle = new ModelRenderer(this, 14, 0);
      this.MalletHandle.addBox(0.0F, 0.0F, 0.0F, 1, 8, 1);
      this.MalletHandle.setRotationPoint(0.5F, 6.7F, 7.5F);
      this.MalletHandle.setTextureSize(64, 64);
      this.MalletHandle.mirror = true;
      this.setRotation(this.MalletHandle, 0.0F, 0.0F, 0.0F);
      this.MalletHead = new ModelRenderer(this, 8, 19);
      this.MalletHead.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
      this.MalletHead.setRotationPoint(-0.5F, 7.0F, 7.0F);
      this.MalletHead.setTextureSize(64, 64);
      this.MalletHead.mirror = true;
      this.setRotation(this.MalletHead, 0.0F, 0.0F, 0.0F);
      this.MasonsHammerHead = new ModelRenderer(this, 0, 23);
      this.MasonsHammerHead.addBox(0.0F, 0.0F, 0.0F, 5, 1, 1);
      this.MasonsHammerHead.setRotationPoint(0.5F, -0.3F, 7.0F);
      this.MasonsHammerHead.setTextureSize(64, 64);
      this.MasonsHammerHead.mirror = true;
      this.setRotation(this.MasonsHammerHead, 0.0F, 0.0F, 0.0F);
      this.MasonsHammerHandle = new ModelRenderer(this, 14, 0);
      this.MasonsHammerHandle.addBox(0.0F, 0.0F, 0.0F, 1, 6, 1);
      this.MasonsHammerHandle.setRotationPoint(2.5F, -0.5F, 6.9F);
      this.MasonsHammerHandle.setTextureSize(64, 64);
      this.MasonsHammerHandle.mirror = true;
      this.setRotation(this.MasonsHammerHandle, 0.0F, 0.0F, 0.0F);
      this.SawBlade = new ModelRenderer(this, 0, 27);
      this.SawBlade.addBox(0.0F, 0.0F, 0.0F, 9, 2, 0);
      this.SawBlade.setRotationPoint(-4.5F, 0.0F, 8.0F);
      this.SawBlade.setTextureSize(64, 64);
      this.SawBlade.mirror = true;
      this.setRotation(this.SawBlade, 0.0F, 1.308997F, ((float)Math.PI / 2F));
      this.SawTeeth = new ModelRenderer(this, 0, 29);
      this.SawTeeth.addBox(-0.2F, 1.6F, 0.0F, 9, 2, 0);
      this.SawTeeth.setRotationPoint(-4.5F, 0.0F, 8.0F);
      this.SawTeeth.setTextureSize(64, 64);
      this.SawTeeth.mirror = true;
      this.setRotation(this.SawTeeth, 0.0F, 1.308997F, 1.396263F);
      this.SawHandle1 = new ModelRenderer(this, 19, 0);
      this.SawHandle1.addBox(0.0F, 0.0F, 0.0F, 1, 4, 1);
      this.SawHandle1.setRotationPoint(-5.0F, -3.5F, 7.5F);
      this.SawHandle1.setTextureSize(64, 64);
      this.SawHandle1.mirror = true;
      this.setRotation(this.SawHandle1, 0.0F, -0.2617994F, 0.0F);
      this.SawHandle2 = new ModelRenderer(this, 19, 0);
      this.SawHandle2.addBox(0.0F, 1.0F, -4.0F, 1, 2, 2);
      this.SawHandle2.setRotationPoint(-5.0F, -3.5F, 7.5F);
      this.SawHandle2.setTextureSize(64, 64);
      this.SawHandle2.mirror = true;
      this.setRotation(this.SawHandle2, 1.518436F, -0.2617994F, 0.0F);
      this.SawHandle3 = new ModelRenderer(this, 19, 0);
      this.SawHandle3.addBox(0.0F, -1.0F, 2.8F, 1, 5, 1);
      this.SawHandle3.setRotationPoint(-5.0F, -3.5F, 7.5F);
      this.SawHandle3.setTextureSize(64, 64);
      this.SawHandle3.mirror = true;
      this.setRotation(this.SawHandle3, -0.0872665F, -0.2617994F, 0.0F);
      this.SawHandle4 = new ModelRenderer(this, 19, 0);
      this.SawHandle4.addBox(0.0F, 1.0F, -1.0F, 1, 2, 1);
      this.SawHandle4.setRotationPoint(-5.0F, -3.5F, 7.5F);
      this.SawHandle4.setTextureSize(64, 64);
      this.SawHandle4.mirror = true;
      this.setRotation(this.SawHandle4, ((float)Math.PI / 2F), -0.2617994F, 0.0F);
      this.Peg1 = new ModelRenderer(this, 4, 9);
      this.Peg1.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1);
      this.Peg1.setRotationPoint(-6.0F, -2.8F, 9.0F);
      this.Peg1.setTextureSize(64, 64);
      this.Peg1.mirror = true;
      this.setRotation(this.Peg1, 0.0F, 0.0F, 0.0872665F);
      this.TongsHandle1 = new ModelRenderer(this, 25, 0);
      this.TongsHandle1.addBox(0.0F, 0.0F, 0.0F, 1, 5, 1);
      this.TongsHandle1.setRotationPoint(-2.0F, 7.0F, 7.0F);
      this.TongsHandle1.setTextureSize(64, 64);
      this.TongsHandle1.mirror = true;
      this.setRotation(this.TongsHandle1, 0.0F, 0.0F, -0.0523599F);
      this.TongsHandle2 = new ModelRenderer(this, 25, 0);
      this.TongsHandle2.addBox(-1.0F, 0.0F, 0.0F, 1, 5, 1);
      this.TongsHandle2.setRotationPoint(-2.0F, 7.0F, 7.0F);
      this.TongsHandle2.setTextureSize(64, 64);
      this.TongsHandle2.mirror = true;
      this.setRotation(this.TongsHandle2, 0.0F, 0.0F, 0.5235988F);
      this.TongsHub = new ModelRenderer(this, 25, 6);
      this.TongsHub.addBox(0.0F, 0.0F, 0.0F, 1, 1, 1);
      this.TongsHub.setRotationPoint(-2.7F, 6.6F, 7.1F);
      this.TongsHub.setTextureSize(64, 64);
      this.TongsHub.mirror = true;
      this.setRotation(this.TongsHub, 0.0F, 0.0F, -0.5759587F);
      this.Tongs1 = new ModelRenderer(this, 25, 0);
      this.Tongs1.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
      this.Tongs1.setRotationPoint(-1.0F, 4.8F, 7.0F);
      this.Tongs1.setTextureSize(64, 64);
      this.Tongs1.mirror = true;
      this.setRotation(this.Tongs1, 0.0F, 0.0F, 0.5235988F);
      this.Tongs2 = new ModelRenderer(this, 25, 0);
      this.Tongs2.addBox(0.0F, 0.0F, 0.0F, 1, 2, 1);
      this.Tongs2.setRotationPoint(-3.0F, 4.6F, 7.0F);
      this.Tongs2.setTextureSize(64, 64);
      this.Tongs2.mirror = true;
      this.setRotation(this.Tongs2, 0.0F, 0.0F, -0.0523599F);
      this.Plans1 = new ModelRenderer(this, 0, 31);
      this.Plans1.addBox(0.0F, 0.0F, 0.0F, 12, 2, 2);
      this.Plans1.setRotationPoint(-6.0F, 9.5F, 3.5F);
      this.Plans1.setTextureSize(64, 64);
      this.Plans1.mirror = true;
      this.setRotation(this.Plans1, -((float)Math.PI / 10F), 0.0F, 0.0F);
      this.Plans2 = new ModelRenderer(this, 0, 35);
      this.Plans2.addBox(0.0F, 0.0F, 0.0F, 10, 1, 2);
      this.Plans2.setRotationPoint(-5.0F, 11.7F, 3.5F);
      this.Plans2.setTextureSize(64, 64);
      this.Plans2.mirror = true;
      this.setRotation(this.Plans2, -0.1570796F, 0.0F, 0.0F);
      this.TackHammerHandle = new ModelRenderer(this, 14, 0);
      this.TackHammerHandle.addBox(0.0F, 0.0F, 0.0F, 1, 4, 1);
      this.TackHammerHandle.setRotationPoint(0.0F, 2.0F, 7.0F);
      this.TackHammerHandle.setTextureSize(64, 64);
      this.TackHammerHandle.mirror = true;
      this.setRotation(this.TackHammerHandle, 0.0F, 0.0F, 0.0F);
      this.TackHammerHead = new ModelRenderer(this, 0, 23);
      this.TackHammerHead.addBox(0.0F, 0.0F, 0.0F, 2, 1, 1);
      this.TackHammerHead.setRotationPoint(-0.5F, 1.5F, 7.1F);
      this.TackHammerHead.setTextureSize(64, 64);
      this.TackHammerHead.mirror = true;
      this.setRotation(this.TackHammerHead, 0.0F, 0.0F, 0.0F);
      this.StraightLine = new ModelRenderer(this, 4, 12);
      this.StraightLine.addBox(0.0F, 0.0F, 0.0F, 4, 2, 2);
      this.StraightLine.setRotationPoint(-4.0F, 2.0F, 7.0F);
      this.StraightLine.setTextureSize(64, 64);
      this.StraightLine.mirror = true;
      this.setRotation(this.StraightLine, 0.0F, 0.0F, -0.837758F);
      this.SledgehammerHead = new ModelRenderer(this, 0, 23);
      this.SledgehammerHead.addBox(0.0F, 0.0F, 0.0F, 3, 2, 2);
      this.SledgehammerHead.setRotationPoint(4.2F, 2.0F, 10.5F);
      this.SledgehammerHead.setTextureSize(64, 64);
      this.SledgehammerHead.mirror = true;
      this.setRotation(this.SledgehammerHead, 0.0349066F, ((float)Math.PI / 2F), 0.0F);
      this.SledgehammerHandle = new ModelRenderer(this, 19, 6);
      this.SledgehammerHandle.addBox(0.0F, 0.0F, 0.0F, 1, 13, 1);
      this.SledgehammerHandle.setRotationPoint(4.6F, 1.8F, 8.5F);
      this.SledgehammerHandle.setTextureSize(64, 64);
      this.SledgehammerHandle.mirror = true;
      this.setRotation(this.SledgehammerHandle, 0.0F, 0.0F, -0.0349066F);
      this.Peg2 = new ModelRenderer(this, 4, 9);
      this.Peg2.addBox(0.0F, 0.0F, 0.0F, 3, 1, 1);
      this.Peg2.setRotationPoint(3.5F, 4.2F, 9.5F);
      this.Peg2.setTextureSize(64, 64);
      this.Peg2.mirror = true;
      this.setRotation(this.Peg2, 0.0F, 0.0F, -0.0872665F);
      this.Peg3 = new ModelRenderer(this, 4, 9);
      this.Peg3.addBox(0.0F, 0.0F, 0.0F, 3, 1, 1);
      this.Peg3.setRotationPoint(3.5F, 4.2F, 7.5F);
      this.Peg3.setTextureSize(64, 64);
      this.Peg3.mirror = true;
      this.setRotation(this.Peg3, 0.0F, 0.0F, -0.0872665F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.MainCusion.render(f5);
      this.Bag1.render(f5);
      this.Bag2.render(f5);
      this.Pouch1.render(f5);
      this.Pouch2.render(f5);
      this.LeftStrap1.render(f5);
      this.LeftStrap2.render(f5);
      this.LeftStrap3.render(f5);
      this.RightStrap1.render(f5);
      this.RightStrap2.render(f5);
      this.RightStrap3.render(f5);
      this.BenchTable.render(f5);
      this.BenchLeg1.render(f5);
      this.BenchLeg2.render(f5);
      this.BenchLeg3.render(f5);
      this.BenchLeg4.render(f5);
      this.Rod1.render(f5);
      this.Rod2.render(f5);
      this.Rod3.render(f5);
      this.Rod4.render(f5);
      this.MalletHandle.render(f5);
      this.MalletHead.render(f5);
      this.MasonsHammerHead.render(f5);
      this.MasonsHammerHandle.render(f5);
      this.SawBlade.render(f5);
      this.SawTeeth.render(f5);
      this.SawHandle1.render(f5);
      this.SawHandle2.render(f5);
      this.SawHandle3.render(f5);
      this.SawHandle4.render(f5);
      this.Peg1.render(f5);
      this.TongsHandle1.render(f5);
      this.TongsHandle2.render(f5);
      this.TongsHub.render(f5);
      this.Tongs1.render(f5);
      this.Tongs2.render(f5);
      this.Plans1.render(f5);
      this.Plans2.render(f5);
      this.TackHammerHandle.render(f5);
      this.TackHammerHead.render(f5);
      this.StraightLine.render(f5);
      this.SledgehammerHead.render(f5);
      this.SledgehammerHandle.render(f5);
      this.Peg2.render(f5);
      this.Peg3.render(f5);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
   }
}
