package fr.thisismac.injector.customclass;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSlimeHat extends ModelBase {
   ModelRenderer Body;
   ModelRenderer Left_Eye;
   ModelRenderer Left_Eyea;
   ModelRenderer Upper_Left_Wing;
   ModelRenderer Lower_Right_Wing;
   ModelRenderer Upper_Right_Wing;
   ModelRenderer Lower_Right_Winga;
   ModelRenderer a1;
   ModelRenderer a2;
   ModelRenderer a3;
   ModelRenderer a4;
   ModelRenderer a5;
   ModelRenderer S1;
   ModelRenderer S2;
   ModelRenderer S3;
   ModelRenderer S4;
   ModelRenderer S5;
   ModelRenderer S6;
   ModelRenderer S7;
   ModelRenderer SA1;
   ModelRenderer SA1a;
   ModelRenderer Right_Antenne_;
   ModelRenderer Right_Antenne_a;
   ModelRenderer Right_Antenne_1;
   ModelRenderer Right_Antenne_1a;
   ModelRenderer Right_Antenne_1b;
   ModelRenderer Right_Antenne_1c;
   ModelRenderer Right_Antenne_1d;
   ModelRenderer Left_Antenne_;
   ModelRenderer Left_Antenne_a;
   ModelRenderer Left_Antenne_1;
   ModelRenderer Left_Antenne_1a;
   ModelRenderer Left_Antenne_1b;
   ModelRenderer Left_Antenne_1c;
   ModelRenderer Left_Antenne_1d;

   public ModelSlimeHat() {
      this.textureWidth = 56;
      this.textureHeight = 29;
      this.Body = new ModelRenderer(this, 0, 13);
      this.Body.addBox(-4.0F, -4.0F, -4.0F, 8, 8, 8);
      this.Body.setRotationPoint(0.0F, 20.0F, 0.0F);
      this.Body.setTextureSize(56, 29);
      this.Body.mirror = true;
      this.setRotation(this.Body, 0.0F, 0.0F, 0.0F);
      this.Left_Eye = new ModelRenderer(this, 5, 0);
      this.Left_Eye.addBox(-1.0F, -2.0F, -1.0F, 2, 4, 1);
      this.Left_Eye.setRotationPoint(3.5F, 19.0F, -3.5F);
      this.Left_Eye.setTextureSize(56, 29);
      this.Left_Eye.mirror = true;
      this.setRotation(this.Left_Eye, 0.0F, 0.0F, 0.0F);
      this.Left_Eyea = new ModelRenderer(this, 5, 0);
      this.Left_Eyea.addBox(-1.0F, -2.0F, -1.0F, 2, 4, 1);
      this.Left_Eyea.setRotationPoint(-3.5F, 19.0F, -3.5F);
      this.Left_Eyea.setTextureSize(56, 29);
      this.Left_Eyea.mirror = true;
      this.setRotation(this.Left_Eyea, 0.0F, 0.0F, 0.0F);
      this.Upper_Left_Wing = new ModelRenderer(this, 40, -8);
      this.Upper_Left_Wing.addBox(0.0F, -8.0F, 0.0F, 0, 8, 8);
      this.Upper_Left_Wing.setRotationPoint(-2.5F, 16.0F, 4.0F);
      this.Upper_Left_Wing.setTextureSize(56, 29);
      this.Upper_Left_Wing.mirror = true;
      this.setRotation(this.Upper_Left_Wing, 0.3490659F, -((float)Math.PI / 4F), 0.0F);
      this.Lower_Right_Wing = new ModelRenderer(this, 42, 2);
      this.Lower_Right_Wing.addBox(0.0F, -6.0F, 0.0F, 0, 6, 6);
      this.Lower_Right_Wing.setRotationPoint(-2.5F, 19.0F, 4.0F);
      this.Lower_Right_Wing.setTextureSize(56, 29);
      this.Lower_Right_Wing.mirror = true;
      this.setRotation(this.Lower_Right_Wing, 0.0F, -0.5235988F, 0.0F);
      this.Upper_Right_Wing = new ModelRenderer(this, 40, -8);
      this.Upper_Right_Wing.addBox(0.0F, -8.0F, 0.0F, 0, 8, 8);
      this.Upper_Right_Wing.setRotationPoint(2.5F, 16.0F, 4.0F);
      this.Upper_Right_Wing.setTextureSize(56, 29);
      this.Upper_Right_Wing.mirror = true;
      this.setRotation(this.Upper_Right_Wing, 0.3490659F, ((float)Math.PI / 4F), 0.0F);
      this.Lower_Right_Winga = new ModelRenderer(this, 42, 2);
      this.Lower_Right_Winga.addBox(0.0F, -6.0F, 0.0F, 0, 6, 6);
      this.Lower_Right_Winga.setRotationPoint(2.5F, 19.0F, 4.0F);
      this.Lower_Right_Winga.setTextureSize(56, 29);
      this.Lower_Right_Winga.mirror = true;
      this.setRotation(this.Lower_Right_Winga, 0.0F, 0.5235988F, 0.0F);
      this.a1 = new ModelRenderer(this, 0, 5);
      this.a1.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4);
      this.a1.setRotationPoint(3.0F, 22.0F, 6.0F);
      this.a1.setTextureSize(56, 29);
      this.a1.mirror = true;
      this.setRotation(this.a1, 0.0F, 0.0F, 0.0F);
      this.a2 = new ModelRenderer(this, 0, 5);
      this.a2.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4);
      this.a2.setRotationPoint(6.0F, 22.0F, 0.0F);
      this.a2.setTextureSize(56, 29);
      this.a2.mirror = true;
      this.setRotation(this.a2, 0.0F, 0.0F, 0.0F);
      this.a3 = new ModelRenderer(this, 0, 5);
      this.a3.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4);
      this.a3.setRotationPoint(-5.0F, 22.0F, -4.0F);
      this.a3.setTextureSize(56, 29);
      this.a3.mirror = true;
      this.setRotation(this.a3, 0.0F, 0.0F, 0.0F);
      this.a4 = new ModelRenderer(this, 0, 5);
      this.a4.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4);
      this.a4.setRotationPoint(-5.0F, 22.0F, 6.0F);
      this.a4.setTextureSize(56, 29);
      this.a4.mirror = true;
      this.setRotation(this.a4, 0.0F, 0.0F, 0.0F);
      this.a5 = new ModelRenderer(this, 0, 5);
      this.a5.addBox(-2.0F, -2.0F, -2.0F, 4, 4, 4);
      this.a5.setRotationPoint(6.0F, 22.0F, -6.0F);
      this.a5.setTextureSize(56, 29);
      this.a5.mirror = true;
      this.setRotation(this.a5, 0.0F, 0.0F, 0.0F);
      this.S1 = new ModelRenderer(this, 12, 5);
      this.S1.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S1.setRotationPoint(3.0F, 23.0F, -5.0F);
      this.S1.setTextureSize(56, 29);
      this.S1.mirror = true;
      this.setRotation(this.S1, 0.0F, 0.0F, 0.0F);
      this.S2 = new ModelRenderer(this, 12, 5);
      this.S2.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S2.setRotationPoint(-7.0F, 23.0F, 4.0F);
      this.S2.setTextureSize(56, 29);
      this.S2.mirror = true;
      this.setRotation(this.S2, 0.0F, 0.0F, 0.0F);
      this.S3 = new ModelRenderer(this, 12, 5);
      this.S3.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S3.setRotationPoint(-2.0F, 23.0F, -6.0F);
      this.S3.setTextureSize(56, 29);
      this.S3.mirror = true;
      this.setRotation(this.S3, 0.0F, 0.0F, 0.0F);
      this.S4 = new ModelRenderer(this, 12, 5);
      this.S4.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S4.setRotationPoint(-5.0F, 23.0F, 2.0F);
      this.S4.setTextureSize(56, 29);
      this.S4.mirror = true;
      this.setRotation(this.S4, 0.0F, 0.0F, 0.0F);
      this.S5 = new ModelRenderer(this, 12, 5);
      this.S5.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S5.setRotationPoint(5.0F, 23.0F, -3.0F);
      this.S5.setTextureSize(56, 29);
      this.S5.mirror = true;
      this.setRotation(this.S5, 0.0F, 0.0F, 0.0F);
      this.S6 = new ModelRenderer(this, 12, 5);
      this.S6.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S6.setRotationPoint(5.0F, 23.0F, 3.0F);
      this.S6.setTextureSize(56, 29);
      this.S6.mirror = true;
      this.setRotation(this.S6, 0.0F, 0.0F, 0.0F);
      this.S7 = new ModelRenderer(this, 12, 5);
      this.S7.addBox(-1.0F, -1.0F, -1.0F, 2, 2, 2);
      this.S7.setRotationPoint(0.0F, 23.0F, 5.0F);
      this.S7.setTextureSize(56, 29);
      this.S7.mirror = true;
      this.setRotation(this.S7, 0.0F, 0.0F, 0.0F);
      this.SA1 = new ModelRenderer(this, 12, 5);
      this.SA1.addBox(0.0F, 0.0F, 0.0F, 2, 2, 2);
      this.SA1.setRotationPoint(-3.5F, 8.5F, -1.0F);
      this.SA1.setTextureSize(56, 29);
      this.SA1.mirror = true;
      this.setRotation(this.SA1, 0.0F, 0.0F, 0.0F);
      this.SA1a = new ModelRenderer(this, 12, 5);
      this.SA1a.addBox(0.0F, 0.0F, 0.0F, 2, 2, 2);
      this.SA1a.setRotationPoint(1.5F, 8.5F, -1.0F);
      this.SA1a.setTextureSize(56, 29);
      this.SA1a.mirror = true;
      this.setRotation(this.SA1a, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_ = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_.addBox(0.0F, 0.0F, 0.0F, 0, 1, 2);
      this.Right_Antenne_.setRotationPoint(2.5F, 9.0F, -3.0F);
      this.Right_Antenne_.setTextureSize(56, 29);
      this.Right_Antenne_.mirror = true;
      this.setRotation(this.Right_Antenne_, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_a = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_a.addBox(0.0F, 0.0F, 0.0F, 0, 1, 2);
      this.Right_Antenne_a.setRotationPoint(2.5F, 15.0F, -3.0F);
      this.Right_Antenne_a.setTextureSize(56, 29);
      this.Right_Antenne_a.mirror = true;
      this.setRotation(this.Right_Antenne_a, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_1 = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_1.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Right_Antenne_1.setRotationPoint(2.5F, 14.0F, -4.0F);
      this.Right_Antenne_1.setTextureSize(56, 29);
      this.Right_Antenne_1.mirror = true;
      this.setRotation(this.Right_Antenne_1, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_1a = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_1a.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Right_Antenne_1a.setRotationPoint(2.5F, 13.0F, -5.0F);
      this.Right_Antenne_1a.setTextureSize(56, 29);
      this.Right_Antenne_1a.mirror = true;
      this.setRotation(this.Right_Antenne_1a, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_1b = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_1b.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Right_Antenne_1b.setRotationPoint(2.5F, 12.0F, -6.0F);
      this.Right_Antenne_1b.setTextureSize(56, 29);
      this.Right_Antenne_1b.mirror = true;
      this.setRotation(this.Right_Antenne_1b, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_1c = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_1c.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Right_Antenne_1c.setRotationPoint(-2.5F, 13.0F, -5.0F);
      this.Right_Antenne_1c.setTextureSize(56, 29);
      this.Right_Antenne_1c.mirror = true;
      this.setRotation(this.Right_Antenne_1c, 0.0F, 0.0F, 0.0F);
      this.Right_Antenne_1d = new ModelRenderer(this, 5, 2);
      this.Right_Antenne_1d.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Right_Antenne_1d.setRotationPoint(2.5F, 10.0F, -4.0F);
      this.Right_Antenne_1d.setTextureSize(56, 29);
      this.Right_Antenne_1d.mirror = true;
      this.setRotation(this.Right_Antenne_1d, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_ = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_.addBox(0.0F, 0.0F, 0.0F, 0, 1, 2);
      this.Left_Antenne_.setRotationPoint(-2.5F, 9.0F, -3.0F);
      this.Left_Antenne_.setTextureSize(56, 29);
      this.Left_Antenne_.mirror = true;
      this.setRotation(this.Left_Antenne_, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_a = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_a.addBox(0.0F, 0.0F, 0.0F, 0, 1, 2);
      this.Left_Antenne_a.setRotationPoint(-2.5F, 15.0F, -3.0F);
      this.Left_Antenne_a.setTextureSize(56, 29);
      this.Left_Antenne_a.mirror = true;
      this.setRotation(this.Left_Antenne_a, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_1 = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_1.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Left_Antenne_1.setRotationPoint(-2.5F, 14.0F, -4.0F);
      this.Left_Antenne_1.setTextureSize(56, 29);
      this.Left_Antenne_1.mirror = true;
      this.setRotation(this.Left_Antenne_1, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_1a = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_1a.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Left_Antenne_1a.setRotationPoint(2.5F, 11.0F, -5.0F);
      this.Left_Antenne_1a.setTextureSize(56, 29);
      this.Left_Antenne_1a.mirror = true;
      this.setRotation(this.Left_Antenne_1a, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_1b = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_1b.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Left_Antenne_1b.setRotationPoint(-2.5F, 12.0F, -6.0F);
      this.Left_Antenne_1b.setTextureSize(56, 29);
      this.Left_Antenne_1b.mirror = true;
      this.setRotation(this.Left_Antenne_1b, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_1c = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_1c.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Left_Antenne_1c.setRotationPoint(-2.5F, 11.0F, -5.0F);
      this.Left_Antenne_1c.setTextureSize(56, 29);
      this.Left_Antenne_1c.mirror = true;
      this.setRotation(this.Left_Antenne_1c, 0.0F, 0.0F, 0.0F);
      this.Left_Antenne_1d = new ModelRenderer(this, 5, 2);
      this.Left_Antenne_1d.addBox(0.0F, 0.0F, 0.0F, 0, 1, 1);
      this.Left_Antenne_1d.setRotationPoint(-2.5F, 10.0F, -4.0F);
      this.Left_Antenne_1d.setTextureSize(56, 29);
      this.Left_Antenne_1d.mirror = true;
      this.setRotation(this.Left_Antenne_1d, 0.0F, 0.0F, 0.0F);
   }

   public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
      super.render(entity, f, f1, f2, f3, f4, f5);
      this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
      this.Body.render(f5);
      this.Left_Eye.render(f5);
      this.Left_Eyea.render(f5);
      this.Upper_Left_Wing.render(f5);
      this.Lower_Right_Wing.render(f5);
      this.Upper_Right_Wing.render(f5);
      this.Lower_Right_Winga.render(f5);
      this.a1.render(f5);
      this.a2.render(f5);
      this.a3.render(f5);
      this.a4.render(f5);
      this.a5.render(f5);
      this.S1.render(f5);
      this.S2.render(f5);
      this.S3.render(f5);
      this.S4.render(f5);
      this.S5.render(f5);
      this.S6.render(f5);
      this.S7.render(f5);
      this.SA1.render(f5);
      this.SA1a.render(f5);
      this.Right_Antenne_.render(f5);
      this.Right_Antenne_a.render(f5);
      this.Right_Antenne_1.render(f5);
      this.Right_Antenne_1a.render(f5);
      this.Right_Antenne_1b.render(f5);
      this.Right_Antenne_1c.render(f5);
      this.Right_Antenne_1d.render(f5);
      this.Left_Antenne_.render(f5);
      this.Left_Antenne_a.render(f5);
      this.Left_Antenne_1.render(f5);
      this.Left_Antenne_1a.render(f5);
      this.Left_Antenne_1b.render(f5);
      this.Left_Antenne_1c.render(f5);
      this.Left_Antenne_1d.render(f5);
   }

   private void setRotation(ModelRenderer model, float x, float y, float z) {
      model.rotateAngleX = x;
      model.rotateAngleY = y;
      model.rotateAngleZ = z;
   }

   public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
      super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
   }
}
